bot:
  token: "951774571:AAEwmnWr3jXpNRULeBC-oOjIGjosIdgVqK0"
  username: "GetInfocryptoBot"
  gift: 0.5
  withdrawchannelID: "-1001527060295"
  transactionchannelID: "-1001515151515"
  gameschannelId: "-1001515151511"
  admins: 78246181,734741043

redisdb:
  user: "default"
  pass: "redispw"
  server: "localhost"
  port: "49153"
  db: "0" #defult db 0

posgresql:
  user: "postgres"
  pass: "docker"
  server: "localhost"
  port: "5432"
  db: "gambelDB"

blockio:
  token: "a54c-cc48-2b69-b76c"
  pin: "p3iphuPo5aswUs4pazed"
  webhookurl: ""